### ISSUE TITLE
Quesqions about pre-process part

### ISSUE THREAD

**Issue by bimbo80C** [FDUDSDE/MAGIC#1]
could u explain what the variable "malicious_entity" in "trace_parser.py" represent? （as following,if I take trace as dataset parameter, what should trace.txt be?）
def read_graphs(dataset):
    malicious_entities = '../data/{}/{}.txt'.format(dataset, dataset)
    f = open(malicious_entities, 'r')
    malicious_entities = set()
    for l in f.readlines():
        malicious_entities.add(l.lstrip().rstrip())
        ...

**Comment by Jimmyokok** [comment]
Go to [ThreaTrace](https://github.com/threaTrace-detector/threaTrace) and you will find these .txt ground truth files in the folder "groundtruth".

**Comment by bimbo80C** [comment]
Thank you! I GOT IT.
