### ISSUE TITLE
Question about the darpa dataset

### ISSUE THREAD

**Issue by kamelferrahi** [FDUDSDE/MAGIC#10]
Hi how did you get the documentation on the darpa dataset n order to know which file  contains the malicious or benign activity

**Comment by Jimmyokok** [comment]
Three ways:

1. Traverse every file and find those activities.
2. Traverse the head of each file, extract the timestamp and see if it is inside the time range of an attack campaign.
3. See which file(s) did previous works use via their papers/github repos.

**Comment by kamelferrahi** [comment]
Thank you for you guidance.
Where Can I find the planning of the attack campaign

**Comment by Jimmyokok** [comment]
There is a ground truth document(TC_Ground_Truth_Report_E3_Update.pdf) officially provided with the data release. It contains when the attack campaigns took place.

**Comment by kamelferrahi** [comment]
Thank You!
