### ISSUE TITLE
Questions about noise reduction

### ISSUE THREAD

**Issue by bingheaaa** [FDUDSDE/MAGIC#11]
I use trace dataset，I would like to ask where noise reduction is reflected in the code

**Comment by Jimmyokok** [comment]
Duplicated with issue#5. You can find answers there.

**Comment by bingheaaa** [comment]
![图片](https://github.com/FDUDSDE/MAGIC/assets/95834619/04f37763-f4df-4909-b589-fc9a428ae44c)
![图片](https://github.com/FDUDSDE/MAGIC/assets/95834619/d396d176-2e81-479d-91a0-4b69eb58a949)
I'm sorry, but I want to know why I can't run it

**Comment by Jimmyokok** [comment]
Fixed the "iteration over a 0-d tensor" bug.
