### ISSUE TITLE
Results about dataset E3-thiea

### ISSUE THREAD

**Issue by Acomand** [FDUDSDE/MAGIC#14]
I'd like to know the test set of dataset thiea.

If I use the graph you provided, I can get the results.

But if I run the program as "python trace_parser.py --dataset theia", the generated file "test0.pkl" is different from the one provided by you. And the result is far from the previous one (regardless of using the checkpoint you provided or retraining the model).

So I'd like to know, is "ta1-theia-e3-official-6r.json.8" the test set? (I have also tried to replace the test set with other files, but the results are also bad). Could you please rerun the trace_parser.py to check the code?

(The results in trace and cadets do not have problem)

Thanks a lot.

**Comment by zmkzmkzmkzmkzmk** [comment]
Do you have any problems reproducing the results of the cadets data set? After I processed the data and used it for model training, I got the following results during verification:
![image](https://github.com/FDUDSDE/MAGIC/assets/148463061/9acaa840-de8e-4fc8-a683-3abf075b53bb)

I repeated the experiment five times and the results were similar.

**Comment by Acomand** [comment]
When I use the dataset E3-cadets, I can get the result which is similar to yours.

But I can not reproduce the result on the dataset E3-theia. I run the code as
`
cd utils && python trace_parser.py --dataset theia

cd ..

python train.py --dataset theia

python eval.py --dataset theia
`
And the result is 
![image](https://github.com/FDUDSDE/MAGIC/assets/51729046/8fb159ff-58c1-494f-95db-38541bcea2f8)

**Comment by Jimmyokok** [comment]
The correct way: Put ta1-theia-e3-official-6r.json to ta1-theia-e3-official-6r.8.json (**including ALL of 0-8**) into the data directory and the parser will read entities from 0-8, parse 0-3 into training graphs and 8 into the test graph. 
I tried to parse E3-THEIA without 4-7 present, resulting in many entities being lost, including several thousand malicious entities, because they are simply defined in 4-7.
Additionally, the peak detection threshold is pre-defined in the eval script. If you are training and detecting from scratch, you could adjust that threshold to make the confusion matrix looks normal, or simply refer to the AUC for threshold-insensitive evaluation.

**Comment by Jimmyokok** [comment]
> Do you have any problems reproducing the results of the cadets data set? After I processed the data and used it for model training, I got the following results during verification: ![image](https://private-user-images.githubusercontent.com/148463061/333856141-9acaa840-de8e-4fc8-a683-3abf075b53bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTY0MDYsIm5iZiI6MTcxNjcxNjEwNiwicGF0aCI6Ii8xNDg0NjMwNjEvMzMzODU2MTQxLTlhY2FhODQwLWRlOGUtNGZjOC1hNjgzLTNhYmYwNzViNTNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwOTM1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTA4NTAzZDRhZDYyODM3NGFjYTM4OWY1MzhhZDA4NzgzMzc4ZjNlYTRmZTk4NmU0MGJiMDQ0NzU3OTNjZDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CxneNblso6Qf5hJFkkFm4O4BooF5WlOgqRURCqZhHZo)
> 
> I repeated the experiment five times and the results were similar.

Similar to above, the printed out confusion matrix could be quite different when the threshold varies. Please refer to the AUC for threshold-insensitive evaluation. 
Meanwhile, the n_neighbors (i.e. k) also affects detection performance and it is more sensitive on E3-CADETS than others.
We are also planning to release a new version of MAGIC, which is more stable, more efficient and easier to reproduce from scratch.

**Comment by Jimmyokok** [comment]
> Do you have any problems reproducing the results of the cadets data set? After I processed the data and used it for model training, I got the following results during verification: ![image](https://private-user-images.githubusercontent.com/148463061/333856141-9acaa840-de8e-4fc8-a683-3abf075b53bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MTgyMDYsIm5iZiI6MTcxNjcxNzkwNiwicGF0aCI6Ii8xNDg0NjMwNjEvMzMzODU2MTQxLTlhY2FhODQwLWRlOGUtNGZjOC1hNjgzLTNhYmYwNzViNTNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxMDA1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTdjM2E4N2U1ODdlZmFmN2IzN2QzMmZkNzAxNDUzN2RmZjdiYmFhN2E2ZWQxODllMGZjZWNhNzQ2MGMyMTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.anpFsZW7f5erIeQe9tWWtDDOutcVTvg1tmf9qpNfl7I)
> 
> I repeated the experiment five times and the results were similar.

For reference, I repeated the evaluation with two different k values, where k = 100 yields AUC= 0.9933 and k = 400 yields AUC=0.9968.

**Comment by Acomand** [comment]
It works, thanks a lot
![image](https://github.com/FDUDSDE/MAGIC/assets/51729046/f078fee8-8848-46b4-ad22-f676bbf19096)
