### ISSUE TITLE
Question about the code of model

### ISSUE THREAD

**Issue by cmh14** [FDUDSDE/MAGIC#16]
Hello sir, I am learning your code for this project and have finished the data-processing part. However, I failed to understand the code of GATConv and GAT classes in /model/gat.py. Especially, the mechanism by which information or parameters are passed in these codes.  Would you mind sharing more detailed documentation of these codes or any other related tutorials?

**Comment by Jimmyokok** [comment]
The GATConv code is simply the official implementation of GATConv of DGL, plus slight modifications on the attention mechanism to include edge features. You will find better documentation at DGL's official API reference.
The GAT code implements stacked layers of GATConv, which is modified from GraphMAE's implementation. This part is less interesting and easy to understand after figuring out how GATConv works.

**Comment by cmh14** [comment]
Thank you sir! I am reading the dgl document right now. Thank you for your answer.
