### ISSUE TITLE
DARPA TC lable

### ISSUE THREAD

**Issue by jiangdie666** [FDUDSDE/MAGIC#18]
我想问一下作者，在对DARPA TC E3 E5数据集研究的时候，有没有考虑或者遇到过公开给边或者（Event）打标签的呀。

**Comment by Jimmyokok** [comment]
给边打标签是比给节点打标签要更容易且更自洽的，但是需要对于攻击本身有比较深入的了解。
同时目前针对E3和E5数据集也并没有能够受到广泛认可的公开标注。
