### ISSUE TITLE
[BUG] Report errors using provided dataset

### ISSUE THREAD

**Issue by Suiji1999** [FDUDSDE/MAGIC#2]
I used the streamspot wget dataset, but the dimensionality of the node features after running data parsing does not match the model you provided. For example, the dimension of streamspot is 20, but your model requires 5

**Comment by ccoverflow** [comment]
Can you run the other dataset successfully? Leave a contact information to communicate?

**Comment by ccoverflow** [comment]
> I used the streamspot wget dataset, but the dimensionality of the node features after running data parsing does not match the model you provided. For example, the dimension of streamspot is 20, but your model requires 5

Can you run the other dataset successfully? Leave a contact information to communicate?

**Comment by Suiji1999** [comment]
I have encountered some problems. You can contact me on QQ 2726608449.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2023年12月27日(星期三) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FDUDSDE/MAGIC] [BUG] Report errors using provided dataset (Issue #2)





  
I used the streamspot wget dataset, but the dimensionality of the node features after running data parsing does not match the model you provided. For example, the dimension of streamspot is 20, but your model requires 5
  
Can you run the other dataset successfully? Leave a contact information to communicate?

**Comment by Suiji1999** [comment]
Please check your email, I send some information to you.

**Comment by Suiji1999** [comment]
> > I used the streamspot wget dataset, but the dimensionality of the node features after running data parsing does not match the model you provided. For example, the dimension of streamspot is 20, but your model requires 5
> 
> Can you run the other dataset successfully? Leave a contact information to communicate?

Please check your email, I send some information to you.

**Comment by Jimmyokok** [comment]
Confirmed that the streamspot checkpoint is bugged. We will update a correct one in a day.

**Comment by Jimmyokok** [comment]
I have retrained and uploaded a new streamspot checkpoint. Please check if it works at your convenience. @Suiji1999

**Comment by Suiji1999** [comment]
> I have retrained and uploaded a new streamspot checkpoint. Please check if it works at your convenience. @Suiji1999

Would you like to leave your contact information?

**Comment by Jimmyokok** [comment]
> > I have retrained and uploaded a new streamspot checkpoint. Please check if it works at your convenience. @Suiji1999
> 
> Would you like to leave your contact information?

You may contact me via jimmyokokok@gmail.com.
