### ISSUE TITLE
The issue of multiple edge types between nodes is not handled in streamspot_parser.py

### ISSUE THREAD

**Issue by yungaoing** [FDUDSDE/MAGIC#20]
```
if not g.has_edge(node_map[src], node_map[dst]):
            g.add_edge(node_map[src], node_map[dst], type=etype)
```
This results in the graph retaining only one edge for multi-edges. According to the paper, this code has no impact on multiple edges of the same type, but for multi-edges of different types, an averaging process is required.

**Comment by Jimmyokok** [comment]
Please refer to issue #5 for reply.
To briefly explain, retaining only one edge for multi-edges is sufficiently effective and we don't want to add extra complexity to the model. The paper describes an edge reduction method theoretically better than this implementation, but the improvement is expected to be only incremental.

**Comment by yungaoing** [comment]
Got it, thank you for your response.
